defaults:
  - _self_
  - model: qwen3-4b
  - dataset: recipenlg_qwen3-4b
  - trainer: recipenlg
experiment_name: Qwen3-4B-CrossEntropyLoss-selected-ingredients-RecipeNLG
log_comet: true
task: question_answering
multitask: True
dataset_source: curated_dataset
max_source_length: 450