defaults:
  - _self_
  - model: smollm3
  - dataset: recipenlg_smollm3
  - trainer: recipenlg-extended-dice
experiment_name: SmolLM3-3B-DiceLoss-RecipeNLG
log_comet: true
task: question_answering
max_source_length: 1024