defaults:
  - _self_
  - model: qwen2-1_5b
  - dataset: recipenlg_qwen2-1_5b
  - trainer: recipenlg_dice_loss
experiment_name: Qwen2-1.5B-DiceLoss-RecipeNLG
log_comet: true
task: question_answering
max_source_length: 1024