defaults:
  - _self_
  - model: qwen3-4b
  - dataset: recipenlg_qwen3-4b
  - trainer: recipenlg_dice_loss-restricted-ingredients
experiment_name: Qwen3-4B-DiceLoss-restricted-ingredients-RecipeNLG
log_comet: true
task: question_answering
dataset_source: curated_dataset
multitask: True
max_source_length: 450
